import eslint from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "dist-pages/**",
      // Generated by the documentation development server and build.
      "apps/site/.ssr/**",
      "**/storybook-static/**",
      "**/coverage/**",
      "benchmarks/api/**",
      // Scanner input samples for business code, not workspace sources.
      "fixtures/migration/**",
      "**/node_modules/**",
      "**/public/wasm/**",
      "**/generated/**",
      "**/wasm/**",
      "**/target/**",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked.map((config) => ({
    ...config,
    files: ["**/*.ts", "**/*.tsx"],
  })),
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.worker,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              regex: "^\\.{1,2}/.*\\.js$",
              message:
                "Use an extensionless relative module specifier in component-library source.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["**/*.mjs"],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // This package is executed directly by Node ESM, so emitted relative imports need the
    // explicit .js extension. Component-library packages retain extensionless specifiers.
    files: ["packages/style-preprocess/src/**/*.ts"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  {
    // Wildcard ambient modules must remain in a script declaration file; a top-level type
    // import would turn them into invalid module augmentations.
    files: ["packages/style-preprocess/client.d.ts"],
    rules: {
      "@typescript-eslint/consistent-type-imports": "off",
    },
  },
);
