// Generates src/generated/styles.ts from styles/index.scss.
// Fails the build when the compiled CSS violates the pingo CSS subset, and
// enforces the token-only rule for component skins.
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compilePingoStyleFile } from "@dopejs/pingo-style-preprocess";

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const entry = path.join(packageDir, "styles", "index.scss");
const outFile = path.join(packageDir, "src", "generated", "styles.ts");

// Token-only enforcement: component skins must reference tokens, never
// literal colors/lengths. Allowed without a token: literal `0` and pure
// keyword values (cursor/justify-content/border-style/transparent/...).
// The pattern anchors at line start, `{`, or `;` so declarations inside
// one-line nested rules (`&:hover { ...; ...; }`) are checked too.
const declarationPattern = /(?:^|[{;])\s*[a-z-]+\s*:\s*([^;{}]+);/gmu;
const keywordOnlyPattern = /^[a-z-]+(?:\s+[a-z-]+)*$/u;
const componentsDir = path.join(packageDir, "styles", "components");
let rejected = false;
for (const file of await readdir(componentsDir)) {
  if (!file.endsWith(".scss")) continue;
  const source = await readFile(path.join(componentsDir, file), "utf8");
  for (const match of source.matchAll(declarationPattern)) {
    const value = (match[1] ?? "").trim();
    if (value.includes("t.$") || value === "0" || keywordOnlyPattern.test(value)) continue;
    console.error(`[pingo-ui] ${file}: literal value "${value}" — use a token from styles/tokens.scss`);
    rejected = true;
  }
}
if (rejected) process.exit(1);

// compilePingoStyleFile always uses the absolute file path as sourceName
// (FilePreprocessOptions carries no sourceName); it returns
// { language, cssText, styleSheet, diagnostics, dependencies }.
const result = await compilePingoStyleFile(entry);
if (result.styleSheet === null || result.cssText === null) {
  for (const diagnostic of result.diagnostics) {
    console.error(
      `[pingo-ui] ${diagnostic.stage}/${diagnostic.code}: ${diagnostic.message}`,
    );
  }
  process.exit(1);
}

const module = `// GENERATED by scripts/build-styles.mjs — do not edit by hand.
import { createStyleSheet, type PingoStyleSheet } from "@dopejs/pingo-style";

/** Compiled pingo-ui skin (shadcn default preset, light + dark). */
export const pingoUiCssText = ${JSON.stringify(result.cssText)};

/** Creates a fresh immutable stylesheet for one pingo root. */
export function createPingoUiStyleSheet(): PingoStyleSheet {
  return createStyleSheet(pingoUiCssText, { sourceName: "@dopejs/pingo-ui" });
}
`;

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, module);
console.log(`[pingo-ui] generated ${path.relative(packageDir, outFile)}`);
