// @generated by scripts/generate-protocol.mjs. Do not edit.

export const ABI_VERSION = 1 as const;
export const PROTOCOL_ALIGNMENT = 4 as const;
export const STREAM_HEADER_BYTES = 16 as const;
export const INSTRUCTION_HEADER_BYTES = 4 as const;
export const RECORD_HEADER_BYTES = 8 as const;
export const NODE_ID_INDEX_BITS = 20 as const;
export const NODE_ID_GENERATION_BITS = 12 as const;
export const NULL_NODE_ID = 4294967295 as const;
export const MUTATION_MAGIC = 1297108804 as const;
export const INPUT_MAGIC = 1229999940 as const;
export const DISPLAY_LIST_MAGIC = 1146113860 as const;
export const GLYPH_RESOURCES_MAGIC = 1196445508 as const;
export const RECORDING_MAGIC = 1380994884 as const;
export const MAX_MUTATION_BYTES = 16777216 as const;
export const MAX_INPUT_BYTES = 16777216 as const;
export const MAX_DISPLAY_LIST_BYTES = 33554432 as const;
export const MAX_GLYPH_RESOURCES_BYTES = 16777216 as const;
export const MAX_RECORDING_BYTES = 67108864 as const;
export const MAX_RESOURCE_BYTES = 8388608 as const;
export const MAX_MUTATION_INSTRUCTIONS = 262144 as const;
export const MAX_INPUT_INSTRUCTIONS = 262144 as const;
export const MAX_DISPLAY_INSTRUCTIONS = 1048576 as const;
export const MAX_GLYPH_RESOURCE_INSTRUCTIONS = 262144 as const;
export const MAX_GLYPH_BITMAP_PIXELS = 16777216 as const;
export const MAX_RECORDING_RECORDS = 1048576 as const;
export const MAX_VIRTUAL_ITEMS = 4000000 as const;
export const VIRTUAL_REFILL_VERSION = 1 as const;
export const VIRTUAL_REFILL_HEADER_WORDS = 2 as const;
export const VIRTUAL_REFILL_RECORD_WORDS = 3 as const;
export const VIRTUAL_REFILL_HEADER_VERSION_INDEX = 0 as const;
export const VIRTUAL_REFILL_HEADER_REQUEST_COUNT_INDEX = 1 as const;
export const VIRTUAL_REFILL_RECORD_NODE_ID_INDEX = 0 as const;
export const VIRTUAL_REFILL_RECORD_START_INDEX = 1 as const;
export const VIRTUAL_REFILL_RECORD_END_INDEX = 2 as const;
export const GLYPH_BITMAP_FIXED_BYTES = null;
export const GLYPH_BITMAP_MINIMUM_BYTES = 28 as const;
export const GLYPH_BITMAP_GLYPH_ID_OFFSET = 0 as const;
export const GLYPH_BITMAP_LEFT_OFFSET = 4 as const;
export const GLYPH_BITMAP_TOP_OFFSET = 8 as const;
export const GLYPH_BITMAP_WIDTH_OFFSET = 12 as const;
export const GLYPH_BITMAP_HEIGHT_OFFSET = 16 as const;
export const GLYPH_BITMAP_DEVICE_PIXEL_RATIO_OFFSET = 20 as const;
export const GLYPH_BITMAP_DATA_BYTES_OFFSET = 24 as const;
export const GLYPH_BITMAP_DATA_OFFSET = 28 as const;
export const GLYPH_PLACEMENT_FIXED_BYTES = 12 as const;
export const GLYPH_PLACEMENT_MINIMUM_BYTES = 12 as const;
export const GLYPH_PLACEMENT_BITMAP_INDEX_OFFSET = 0 as const;
export const GLYPH_PLACEMENT_X_OFFSET = 4 as const;
export const GLYPH_PLACEMENT_Y_OFFSET = 8 as const;
export const FRAME_DIAGNOSTICS_VERSION = 2 as const;
export const FRAME_DIAGNOSTICS_WORDS = 19 as const;
export const FRAME_DIAGNOSTICS_VERSION_INDEX = 0 as const;
export const FRAME_DIAGNOSTICS_FRAME_SEQ_INDEX = 1 as const;
export const FRAME_DIAGNOSTICS_SCENE_NODES_INDEX = 2 as const;
export const FRAME_DIAGNOSTICS_DIRTY_LAYOUT_NODES_INDEX = 3 as const;
export const FRAME_DIAGNOSTICS_DIRTY_PAINT_NODES_INDEX = 4 as const;
export const FRAME_DIAGNOSTICS_DIRTY_PAINT_SELF_NODES_INDEX = 5 as const;
export const FRAME_DIAGNOSTICS_DIRTY_HIT_NODES_INDEX = 6 as const;
export const FRAME_DIAGNOSTICS_DIRTY_SEMANTICS_NODES_INDEX = 7 as const;
export const FRAME_DIAGNOSTICS_LAYOUT_CHANGED_NODES_INDEX = 8 as const;
export const FRAME_DIAGNOSTICS_LAYOUT_VISITED_NODES_INDEX = 9 as const;
export const FRAME_DIAGNOSTICS_DISPLAY_COMMANDS_INDEX = 10 as const;
export const FRAME_DIAGNOSTICS_PAINT_REBUILT_INDEX = 11 as const;
export const FRAME_DIAGNOSTICS_PICTURE_BUILDS_INDEX = 12 as const;
export const FRAME_DIAGNOSTICS_PICTURE_CACHE_HITS_INDEX = 13 as const;
export const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_BUILDS_INDEX = 14 as const;
export const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_CACHE_HITS_INDEX = 15 as const;
export const FRAME_DIAGNOSTICS_OVER_INVALIDATED_FRAMES_INDEX = 16 as const;
export const FRAME_DIAGNOSTICS_PICTURE_HASH_LOW_INDEX = 17 as const;
export const FRAME_DIAGNOSTICS_PICTURE_HASH_HIGH_INDEX = 18 as const;
export const RESOURCE_ENCODING_VERSION = 1 as const;
export const SOLID_PAINT_RESOURCE_VARIANT = 1 as const;
export const SOLID_PAINT_RESOURCE_FIXED_BYTES = 8 as const;
export const SOLID_PAINT_RESOURCE_MINIMUM_BYTES = 8 as const;
export const SOLID_PAINT_VERSION_OFFSET = 0 as const;
export const SOLID_PAINT_VARIANT_OFFSET = 1 as const;
export const SOLID_PAINT_RED_OFFSET = 4 as const;
export const SOLID_PAINT_GREEN_OFFSET = 5 as const;
export const SOLID_PAINT_BLUE_OFFSET = 6 as const;
export const SOLID_PAINT_ALPHA_OFFSET = 7 as const;
export const TEXT_STYLE_RESOURCE_VARIANT = 1 as const;
export const TEXT_STYLE_RESOURCE_FIXED_BYTES = null;
export const TEXT_STYLE_RESOURCE_MINIMUM_BYTES = 24 as const;
export const TEXT_STYLE_VERSION_OFFSET = 0 as const;
export const TEXT_STYLE_VARIANT_OFFSET = 1 as const;
export const TEXT_STYLE_PAINT_ID_OFFSET = 4 as const;
export const TEXT_STYLE_FONT_SIZE_OFFSET = 8 as const;
export const TEXT_STYLE_LINE_HEIGHT_OFFSET = 12 as const;
export const TEXT_STYLE_WEIGHT_OFFSET = 16 as const;
export const TEXT_STYLE_FAMILY_BYTES_OFFSET = 20 as const;
export const TEXT_STYLE_FAMILY_OFFSET = 24 as const;
export const AFFINE_RESOURCE_VARIANT = 1 as const;
export const AFFINE_RESOURCE_FIXED_BYTES = 28 as const;
export const AFFINE_RESOURCE_MINIMUM_BYTES = 28 as const;
export const AFFINE_VERSION_OFFSET = 0 as const;
export const AFFINE_VARIANT_OFFSET = 1 as const;
export const AFFINE_A_OFFSET = 4 as const;
export const AFFINE_B_OFFSET = 8 as const;
export const AFFINE_C_OFFSET = 12 as const;
export const AFFINE_D_OFFSET = 16 as const;
export const AFFINE_E_OFFSET = 20 as const;
export const AFFINE_F_OFFSET = 24 as const;

export enum RecordingRecordKind {
  Mutation = 1,
  Input = 2,
}

export enum MutationOpcode {
  CreateNode = 1,
  RemoveNode = 2,
  Reparent = 3,
  SetF32 = 16,
  SetVec4 = 17,
  SetRef = 18,
  SetFlags = 19,
  ClearProp = 20,
  SetTextRun = 32,
  DefineResource = 48,
  ReleaseResource = 49,
  ScrollTo = 64,
  ConfigureVirtualList = 65,
  SetVirtualItem = 66,
  Commit = 240,
}

export const MUTATION_LAYOUTS = {
  [MutationOpcode.CreateNode]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.RemoveNode]: { fixedBytes: 8, minimumBytes: 8 },
  [MutationOpcode.Reparent]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetF32]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetVec4]: { fixedBytes: 28, minimumBytes: 28 },
  [MutationOpcode.SetRef]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetFlags]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.ClearProp]: { fixedBytes: 12, minimumBytes: 12 },
  [MutationOpcode.SetTextRun]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.DefineResource]: { fixedBytes: null, minimumBytes: 16 },
  [MutationOpcode.ReleaseResource]: { fixedBytes: 8, minimumBytes: 8 },
  [MutationOpcode.ScrollTo]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.ConfigureVirtualList]: { fixedBytes: 28, minimumBytes: 28 },
  [MutationOpcode.SetVirtualItem]: { fixedBytes: 12, minimumBytes: 12 },
  [MutationOpcode.Commit]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum InputOpcode {
  Replace = 1,
  Insert = 2,
  DeleteBackward = 3,
  DeleteForward = 4,
  SetSelection = 5,
  BeginComposition = 6,
  UpdateComposition = 7,
  CommitComposition = 8,
  CancelComposition = 9,
  Undo = 10,
  Redo = 11,
  ScrollBegin = 32,
  ScrollDelta = 33,
  ScrollEnd = 34,
  ScrollCancel = 35,
  Commit = 240,
}

export const INPUT_LAYOUTS = {
  [InputOpcode.Replace]: { fixedBytes: null, minimumBytes: 28 },
  [InputOpcode.Insert]: { fixedBytes: null, minimumBytes: 20 },
  [InputOpcode.DeleteBackward]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.DeleteForward]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.SetSelection]: { fixedBytes: 28, minimumBytes: 28 },
  [InputOpcode.BeginComposition]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.UpdateComposition]: { fixedBytes: null, minimumBytes: 20 },
  [InputOpcode.CommitComposition]: { fixedBytes: null, minimumBytes: 24 },
  [InputOpcode.CancelComposition]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.Undo]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.Redo]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.ScrollBegin]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.ScrollDelta]: { fixedBytes: 20, minimumBytes: 20 },
  [InputOpcode.ScrollEnd]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.ScrollCancel]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.Commit]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum DisplayOpcode {
  Save = 1,
  Restore = 2,
  Transform = 3,
  ClipRect = 4,
  Alpha = 5,
  FillRect = 16,
  FillRRect = 17,
  FillPath = 18,
  DrawGlyphRun = 32,
  DrawTextFallback = 33,
  DrawImage = 34,
  DrawPicture = 35,
}

export const DISPLAY_LAYOUTS = {
  [DisplayOpcode.Save]: { fixedBytes: 4, minimumBytes: 4 },
  [DisplayOpcode.Restore]: { fixedBytes: 4, minimumBytes: 4 },
  [DisplayOpcode.Transform]: { fixedBytes: 28, minimumBytes: 28 },
  [DisplayOpcode.ClipRect]: { fixedBytes: 20, minimumBytes: 20 },
  [DisplayOpcode.Alpha]: { fixedBytes: 8, minimumBytes: 8 },
  [DisplayOpcode.FillRect]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.FillRRect]: { fixedBytes: 40, minimumBytes: 40 },
  [DisplayOpcode.FillPath]: { fixedBytes: 12, minimumBytes: 12 },
  [DisplayOpcode.DrawGlyphRun]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.DrawTextFallback]: { fixedBytes: 20, minimumBytes: 20 },
  [DisplayOpcode.DrawImage]: { fixedBytes: 40, minimumBytes: 40 },
  [DisplayOpcode.DrawPicture]: { fixedBytes: 16, minimumBytes: 16 },
} as const;

export enum GlyphResourceOpcode {
  DefineGlyphSpan = 1,
  ReleaseGlyphSpan = 2,
}

export const GLYPH_RESOURCE_LAYOUTS = {
  [GlyphResourceOpcode.DefineGlyphSpan]: { fixedBytes: null, minimumBytes: 24 },
  [GlyphResourceOpcode.ReleaseGlyphSpan]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum NodeKind {
  Root = 1,
  Container = 2,
  Text = 3,
  Image = 4,
  EditableText = 5,
  Scroll = 6,
}

export enum ResourceKind {
  Utf8String = 1,
  Image = 2,
  Path = 3,
  Font = 4,
  GlyphSpan = 5,
  Paint = 6,
  TextStyle = 7,
  Affine = 8,
}

export enum Prop {
  Width = 1,
  Height = 2,
  MinWidth = 3,
  MinHeight = 4,
  MaxWidth = 5,
  MaxHeight = 6,
  Padding = 7,
  Color = 16,
  BackgroundColor = 17,
  Opacity = 18,
  Transform = 19,
  Text = 32,
  FontSize = 33,
  OnTap = 48,
  SemanticRole = 64,
  SemanticLabel = 65,
  SemanticValue = 66,
}

export const enum Invalidation {
  None = 0,
  Layout = 1,
  Paint = 2,
  PaintSelf = 4,
  Hit = 8,
  Semantics = 16,
}

export const PROP_METADATA = {
  1: { name: "Width", valueType: "f32", resourceKind: null, invalidation: 3 },
  2: { name: "Height", valueType: "f32", resourceKind: null, invalidation: 3 },
  3: {
    name: "MinWidth",
    valueType: "f32",
    resourceKind: null,
    invalidation: 3,
  },
  4: {
    name: "MinHeight",
    valueType: "f32",
    resourceKind: null,
    invalidation: 3,
  },
  5: {
    name: "MaxWidth",
    valueType: "f32",
    resourceKind: null,
    invalidation: 3,
  },
  6: {
    name: "MaxHeight",
    valueType: "f32",
    resourceKind: null,
    invalidation: 3,
  },
  7: {
    name: "Padding",
    valueType: "vec4",
    resourceKind: null,
    invalidation: 3,
  },
  16: {
    name: "Color",
    valueType: "ref",
    resourceKind: ResourceKind.Paint,
    invalidation: 2,
  },
  17: {
    name: "BackgroundColor",
    valueType: "ref",
    resourceKind: ResourceKind.Paint,
    invalidation: 2,
  },
  18: {
    name: "Opacity",
    valueType: "f32",
    resourceKind: null,
    invalidation: 4,
  },
  19: {
    name: "Transform",
    valueType: "ref",
    resourceKind: ResourceKind.Affine,
    invalidation: 10,
  },
  32: {
    name: "Text",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 19,
  },
  33: {
    name: "FontSize",
    valueType: "f32",
    resourceKind: null,
    invalidation: 3,
  },
  48: { name: "OnTap", valueType: "ref", resourceKind: null, invalidation: 0 },
  64: {
    name: "SemanticRole",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
  65: {
    name: "SemanticLabel",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
  66: {
    name: "SemanticValue",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
} as const;
