// @generated by scripts/generate-protocol.mjs. Do not edit.

pub const ABI_VERSION: u16 = 1;
pub const PROTOCOL_ALIGNMENT: usize = 4;
pub const STREAM_HEADER_BYTES: usize = 16;
pub const INSTRUCTION_HEADER_BYTES: usize = 4;
pub const RECORD_HEADER_BYTES: usize = 8;
pub const NODE_ID_INDEX_BITS: u32 = 20;
pub const NODE_ID_GENERATION_BITS: u32 = 12;
pub const NULL_NODE_ID: u32 = 4294967295;
pub const MUTATION_MAGIC: u32 = 1297108804;
pub const INPUT_MAGIC: u32 = 1229999940;
pub const DISPLAY_LIST_MAGIC: u32 = 1146113860;
pub const RECORDING_MAGIC: u32 = 1380994884;
pub const MAX_MUTATION_BYTES: usize = 16777216;
pub const MAX_INPUT_BYTES: usize = 16777216;
pub const MAX_DISPLAY_LIST_BYTES: usize = 33554432;
pub const MAX_RECORDING_BYTES: usize = 67108864;
pub const MAX_RESOURCE_BYTES: usize = 8388608;
pub const MAX_MUTATION_INSTRUCTIONS: u32 = 262144;
pub const MAX_INPUT_INSTRUCTIONS: u32 = 262144;
pub const MAX_DISPLAY_INSTRUCTIONS: u32 = 1048576;
pub const MAX_RECORDING_RECORDS: u32 = 1048576;
pub const FRAME_DIAGNOSTICS_VERSION: u32 = 2;
pub const FRAME_DIAGNOSTICS_WORDS: usize = 19;
pub const FRAME_DIAGNOSTICS_VERSION_INDEX: usize = 0;
pub const FRAME_DIAGNOSTICS_FRAME_SEQ_INDEX: usize = 1;
pub const FRAME_DIAGNOSTICS_SCENE_NODES_INDEX: usize = 2;
pub const FRAME_DIAGNOSTICS_DIRTY_LAYOUT_NODES_INDEX: usize = 3;
pub const FRAME_DIAGNOSTICS_DIRTY_PAINT_NODES_INDEX: usize = 4;
pub const FRAME_DIAGNOSTICS_DIRTY_PAINT_SELF_NODES_INDEX: usize = 5;
pub const FRAME_DIAGNOSTICS_DIRTY_HIT_NODES_INDEX: usize = 6;
pub const FRAME_DIAGNOSTICS_DIRTY_SEMANTICS_NODES_INDEX: usize = 7;
pub const FRAME_DIAGNOSTICS_LAYOUT_CHANGED_NODES_INDEX: usize = 8;
pub const FRAME_DIAGNOSTICS_LAYOUT_VISITED_NODES_INDEX: usize = 9;
pub const FRAME_DIAGNOSTICS_DISPLAY_COMMANDS_INDEX: usize = 10;
pub const FRAME_DIAGNOSTICS_PAINT_REBUILT_INDEX: usize = 11;
pub const FRAME_DIAGNOSTICS_PICTURE_BUILDS_INDEX: usize = 12;
pub const FRAME_DIAGNOSTICS_PICTURE_CACHE_HITS_INDEX: usize = 13;
pub const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_BUILDS_INDEX: usize = 14;
pub const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_CACHE_HITS_INDEX: usize = 15;
pub const FRAME_DIAGNOSTICS_OVER_INVALIDATED_FRAMES_INDEX: usize = 16;
pub const FRAME_DIAGNOSTICS_PICTURE_HASH_LOW_INDEX: usize = 17;
pub const FRAME_DIAGNOSTICS_PICTURE_HASH_HIGH_INDEX: usize = 18;
pub const RESOURCE_ENCODING_VERSION: u8 = 1;
pub const SOLID_PAINT_RESOURCE_VARIANT: u8 = 1;
pub const SOLID_PAINT_RESOURCE_FIXED_BYTES: Option<usize> = Some(8);
pub const SOLID_PAINT_RESOURCE_MINIMUM_BYTES: usize = 8;
pub const SOLID_PAINT_VERSION_OFFSET: usize = 0;
pub const SOLID_PAINT_VARIANT_OFFSET: usize = 1;
pub const SOLID_PAINT_RED_OFFSET: usize = 4;
pub const SOLID_PAINT_GREEN_OFFSET: usize = 5;
pub const SOLID_PAINT_BLUE_OFFSET: usize = 6;
pub const SOLID_PAINT_ALPHA_OFFSET: usize = 7;
pub const TEXT_STYLE_RESOURCE_VARIANT: u8 = 1;
pub const TEXT_STYLE_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const TEXT_STYLE_RESOURCE_MINIMUM_BYTES: usize = 24;
pub const TEXT_STYLE_VERSION_OFFSET: usize = 0;
pub const TEXT_STYLE_VARIANT_OFFSET: usize = 1;
pub const TEXT_STYLE_PAINT_ID_OFFSET: usize = 4;
pub const TEXT_STYLE_FONT_SIZE_OFFSET: usize = 8;
pub const TEXT_STYLE_LINE_HEIGHT_OFFSET: usize = 12;
pub const TEXT_STYLE_WEIGHT_OFFSET: usize = 16;
pub const TEXT_STYLE_FAMILY_BYTES_OFFSET: usize = 20;
pub const TEXT_STYLE_FAMILY_OFFSET: usize = 24;
pub const AFFINE_RESOURCE_VARIANT: u8 = 1;
pub const AFFINE_RESOURCE_FIXED_BYTES: Option<usize> = Some(28);
pub const AFFINE_RESOURCE_MINIMUM_BYTES: usize = 28;
pub const AFFINE_VERSION_OFFSET: usize = 0;
pub const AFFINE_VARIANT_OFFSET: usize = 1;
pub const AFFINE_A_OFFSET: usize = 4;
pub const AFFINE_B_OFFSET: usize = 8;
pub const AFFINE_C_OFFSET: usize = 12;
pub const AFFINE_D_OFFSET: usize = 16;
pub const AFFINE_E_OFFSET: usize = 20;
pub const AFFINE_F_OFFSET: usize = 24;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum RecordingRecordKind {
    Mutation = 1,
    Input = 2,
}

impl RecordingRecordKind {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Mutation),
            2 => Some(Self::Input),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum MutationOpcode {
    CreateNode = 1,
    RemoveNode = 2,
    Reparent = 3,
    SetF32 = 16,
    SetVec4 = 17,
    SetRef = 18,
    SetFlags = 19,
    ClearProp = 20,
    SetTextRun = 32,
    DefineResource = 48,
    ReleaseResource = 49,
    ScrollTo = 64,
    Commit = 240,
}

impl MutationOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::CreateNode),
            2 => Some(Self::RemoveNode),
            3 => Some(Self::Reparent),
            16 => Some(Self::SetF32),
            17 => Some(Self::SetVec4),
            18 => Some(Self::SetRef),
            19 => Some(Self::SetFlags),
            20 => Some(Self::ClearProp),
            32 => Some(Self::SetTextRun),
            48 => Some(Self::DefineResource),
            49 => Some(Self::ReleaseResource),
            64 => Some(Self::ScrollTo),
            240 => Some(Self::Commit),
            _ => None,
        }
    }
}

impl MutationOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::CreateNode => Some(20),
            Self::RemoveNode => Some(8),
            Self::Reparent => Some(16),
            Self::SetF32 => Some(16),
            Self::SetVec4 => Some(28),
            Self::SetRef => Some(16),
            Self::SetFlags => Some(16),
            Self::ClearProp => Some(12),
            Self::SetTextRun => Some(16),
            Self::DefineResource => None,
            Self::ReleaseResource => Some(8),
            Self::ScrollTo => Some(20),
            Self::Commit => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::CreateNode => 20,
            Self::RemoveNode => 8,
            Self::Reparent => 16,
            Self::SetF32 => 16,
            Self::SetVec4 => 28,
            Self::SetRef => 16,
            Self::SetFlags => 16,
            Self::ClearProp => 12,
            Self::SetTextRun => 16,
            Self::DefineResource => 16,
            Self::ReleaseResource => 8,
            Self::ScrollTo => 20,
            Self::Commit => 8,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum InputOpcode {
    Replace = 1,
    Insert = 2,
    DeleteBackward = 3,
    DeleteForward = 4,
    SetSelection = 5,
    BeginComposition = 6,
    UpdateComposition = 7,
    CommitComposition = 8,
    CancelComposition = 9,
    Undo = 10,
    Redo = 11,
    Commit = 240,
}

impl InputOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Replace),
            2 => Some(Self::Insert),
            3 => Some(Self::DeleteBackward),
            4 => Some(Self::DeleteForward),
            5 => Some(Self::SetSelection),
            6 => Some(Self::BeginComposition),
            7 => Some(Self::UpdateComposition),
            8 => Some(Self::CommitComposition),
            9 => Some(Self::CancelComposition),
            10 => Some(Self::Undo),
            11 => Some(Self::Redo),
            240 => Some(Self::Commit),
            _ => None,
        }
    }
}

impl InputOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Replace => None,
            Self::Insert => None,
            Self::DeleteBackward => Some(16),
            Self::DeleteForward => Some(16),
            Self::SetSelection => Some(28),
            Self::BeginComposition => Some(16),
            Self::UpdateComposition => None,
            Self::CommitComposition => None,
            Self::CancelComposition => Some(16),
            Self::Undo => Some(16),
            Self::Redo => Some(16),
            Self::Commit => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Replace => 28,
            Self::Insert => 20,
            Self::DeleteBackward => 16,
            Self::DeleteForward => 16,
            Self::SetSelection => 28,
            Self::BeginComposition => 16,
            Self::UpdateComposition => 20,
            Self::CommitComposition => 24,
            Self::CancelComposition => 16,
            Self::Undo => 16,
            Self::Redo => 16,
            Self::Commit => 8,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum DisplayOpcode {
    Save = 1,
    Restore = 2,
    Transform = 3,
    ClipRect = 4,
    Alpha = 5,
    FillRect = 16,
    FillRRect = 17,
    FillPath = 18,
    DrawGlyphRun = 32,
    DrawTextFallback = 33,
    DrawImage = 34,
    DrawPicture = 35,
}

impl DisplayOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Save),
            2 => Some(Self::Restore),
            3 => Some(Self::Transform),
            4 => Some(Self::ClipRect),
            5 => Some(Self::Alpha),
            16 => Some(Self::FillRect),
            17 => Some(Self::FillRRect),
            18 => Some(Self::FillPath),
            32 => Some(Self::DrawGlyphRun),
            33 => Some(Self::DrawTextFallback),
            34 => Some(Self::DrawImage),
            35 => Some(Self::DrawPicture),
            _ => None,
        }
    }
}

impl DisplayOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Save => Some(4),
            Self::Restore => Some(4),
            Self::Transform => Some(28),
            Self::ClipRect => Some(20),
            Self::Alpha => Some(8),
            Self::FillRect => Some(24),
            Self::FillRRect => Some(40),
            Self::FillPath => Some(12),
            Self::DrawGlyphRun => Some(24),
            Self::DrawTextFallback => Some(20),
            Self::DrawImage => Some(40),
            Self::DrawPicture => Some(16),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Save => 4,
            Self::Restore => 4,
            Self::Transform => 28,
            Self::ClipRect => 20,
            Self::Alpha => 8,
            Self::FillRect => 24,
            Self::FillRRect => 40,
            Self::FillPath => 12,
            Self::DrawGlyphRun => 24,
            Self::DrawTextFallback => 20,
            Self::DrawImage => 40,
            Self::DrawPicture => 16,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum NodeKind {
    Root = 1,
    Container = 2,
    Text = 3,
    Image = 4,
    EditableText = 5,
    Scroll = 6,
}

impl NodeKind {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Root),
            2 => Some(Self::Container),
            3 => Some(Self::Text),
            4 => Some(Self::Image),
            5 => Some(Self::EditableText),
            6 => Some(Self::Scroll),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ResourceKind {
    Utf8String = 1,
    Image = 2,
    Path = 3,
    Font = 4,
    GlyphSpan = 5,
    Paint = 6,
    TextStyle = 7,
    Affine = 8,
}

impl ResourceKind {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Utf8String),
            2 => Some(Self::Image),
            3 => Some(Self::Path),
            4 => Some(Self::Font),
            5 => Some(Self::GlyphSpan),
            6 => Some(Self::Paint),
            7 => Some(Self::TextStyle),
            8 => Some(Self::Affine),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum Prop {
    Width = 1,
    Height = 2,
    MinWidth = 3,
    MinHeight = 4,
    MaxWidth = 5,
    MaxHeight = 6,
    Padding = 7,
    Color = 16,
    BackgroundColor = 17,
    Opacity = 18,
    Transform = 19,
    Text = 32,
    FontSize = 33,
    OnTap = 48,
    SemanticRole = 64,
    SemanticLabel = 65,
    SemanticValue = 66,
}

impl Prop {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Width),
            2 => Some(Self::Height),
            3 => Some(Self::MinWidth),
            4 => Some(Self::MinHeight),
            5 => Some(Self::MaxWidth),
            6 => Some(Self::MaxHeight),
            7 => Some(Self::Padding),
            16 => Some(Self::Color),
            17 => Some(Self::BackgroundColor),
            18 => Some(Self::Opacity),
            19 => Some(Self::Transform),
            32 => Some(Self::Text),
            33 => Some(Self::FontSize),
            48 => Some(Self::OnTap),
            64 => Some(Self::SemanticRole),
            65 => Some(Self::SemanticLabel),
            66 => Some(Self::SemanticValue),
            _ => None,
        }
    }
}

impl Prop {
    #[must_use]
    pub const fn invalidation(self) -> Invalidation {
        match self {
            Self::Width => Invalidation::from_bits(3),
            Self::Height => Invalidation::from_bits(3),
            Self::MinWidth => Invalidation::from_bits(3),
            Self::MinHeight => Invalidation::from_bits(3),
            Self::MaxWidth => Invalidation::from_bits(3),
            Self::MaxHeight => Invalidation::from_bits(3),
            Self::Padding => Invalidation::from_bits(3),
            Self::Color => Invalidation::from_bits(2),
            Self::BackgroundColor => Invalidation::from_bits(2),
            Self::Opacity => Invalidation::from_bits(4),
            Self::Transform => Invalidation::from_bits(10),
            Self::Text => Invalidation::from_bits(19),
            Self::FontSize => Invalidation::from_bits(3),
            Self::OnTap => Invalidation::from_bits(0),
            Self::SemanticRole => Invalidation::from_bits(16),
            Self::SemanticLabel => Invalidation::from_bits(16),
            Self::SemanticValue => Invalidation::from_bits(16),
        }
    }

    #[must_use]
    pub const fn value_type(self) -> PropValueType {
        match self {
            Self::Width => PropValueType::F32,
            Self::Height => PropValueType::F32,
            Self::MinWidth => PropValueType::F32,
            Self::MinHeight => PropValueType::F32,
            Self::MaxWidth => PropValueType::F32,
            Self::MaxHeight => PropValueType::F32,
            Self::Padding => PropValueType::Vec4,
            Self::Color => PropValueType::Ref,
            Self::BackgroundColor => PropValueType::Ref,
            Self::Opacity => PropValueType::F32,
            Self::Transform => PropValueType::Ref,
            Self::Text => PropValueType::Ref,
            Self::FontSize => PropValueType::F32,
            Self::OnTap => PropValueType::Ref,
            Self::SemanticRole => PropValueType::Ref,
            Self::SemanticLabel => PropValueType::Ref,
            Self::SemanticValue => PropValueType::Ref,
        }
    }

    #[must_use]
    pub const fn resource_kind(self) -> Option<ResourceKind> {
        match self {
            Self::Width => None,
            Self::Height => None,
            Self::MinWidth => None,
            Self::MinHeight => None,
            Self::MaxWidth => None,
            Self::MaxHeight => None,
            Self::Padding => None,
            Self::Color => Some(ResourceKind::Paint),
            Self::BackgroundColor => Some(ResourceKind::Paint),
            Self::Opacity => None,
            Self::Transform => Some(ResourceKind::Affine),
            Self::Text => Some(ResourceKind::Utf8String),
            Self::FontSize => None,
            Self::OnTap => None,
            Self::SemanticRole => Some(ResourceKind::Utf8String),
            Self::SemanticLabel => Some(ResourceKind::Utf8String),
            Self::SemanticValue => Some(ResourceKind::Utf8String),
        }
    }
}
